/**
 * X 平台 AI 领域高热度账号推荐池（100 条）
 * 由 scripts/seed-recommendation-pool.ts 写入 sources.in_recommendation_pool
 */
export type RecommendationPoolEntry = {
  handle: string
  name: string
  description: string
  sourceType: 'blogger' | 'media' | 'academic'
}

export const RECOMMENDATION_POOL: RecommendationPoolEntry[] = [
  { handle: 'karpathy', name: 'Andrej Karpathy', description: 'AI 教育与工程，前 Tesla AI / OpenAI', sourceType: 'blogger' },
  { handle: 'sama', name: 'Sam Altman', description: 'OpenAI CEO', sourceType: 'blogger' },
  { handle: 'ylecun', name: 'Yann LeCun', description: 'Meta 首席 AI 科学家，图灵奖得主', sourceType: 'blogger' },
  { handle: 'ilyasut', name: 'Ilya Sutskever', description: 'OpenAI 联合创始人，SSI 创始人', sourceType: 'blogger' },
  { handle: 'DarioAmodei', name: 'Dario Amodei', description: 'Anthropic CEO', sourceType: 'blogger' },
  { handle: 'demishassabis', name: 'Demis Hassabis', description: 'Google DeepMind CEO', sourceType: 'blogger' },
  { handle: 'GeoffHinton', name: 'Geoffrey Hinton', description: '深度学习先驱，图灵奖得主', sourceType: 'blogger' },
  { handle: 'AndrewYNg', name: 'Andrew Ng', description: 'DeepLearning.AI 创始人', sourceType: 'blogger' },
  { handle: 'drfeifei', name: 'Fei-Fei Li', description: '斯坦福 HAI 联席主任', sourceType: 'blogger' },
  { handle: 'GaryMarcus', name: 'Gary Marcus', description: 'AI 批评与认知科学', sourceType: 'blogger' },
  { handle: 'hardmaru', name: 'David Ha', description: '生成模型与强化学习研究', sourceType: 'blogger' },
  { handle: 'goodfellow_ian', name: 'Ian Goodfellow', description: 'GAN 发明者', sourceType: 'blogger' },
  { handle: 'JeffDean', name: 'Jeff Dean', description: 'Google 首席科学家', sourceType: 'blogger' },
  { handle: 'percyliang', name: 'Percy Liang', description: '斯坦福 NLP / 基础模型评估', sourceType: 'blogger' },
  { handle: 'ch402', name: 'Chris Olah', description: '神经网络可解释性', sourceType: 'blogger' },
  { handle: 'clementdelangue', name: 'Clément Delangue', description: 'Hugging Face CEO', sourceType: 'blogger' },
  { handle: 'AravSrinivas', name: 'Aravind Srinivas', description: 'Perplexity CEO', sourceType: 'blogger' },
  { handle: 'emollick', name: 'Ethan Mollick', description: 'AI 与创业教育（沃顿）', sourceType: 'blogger' },
  { handle: 'bindureddy', name: 'Bindu Reddy', description: 'Abacus.AI CEO', sourceType: 'blogger' },
  { handle: 'rowancheung', name: 'Rowan Cheung', description: 'The Rundown AI 创始人', sourceType: 'blogger' },
  { handle: 'swyx', name: 'Shawn Wang', description: 'AI 工程与 Latent Space', sourceType: 'blogger' },
  { handle: 'simonw', name: 'Simon Willison', description: 'LLM 工具与 Datasette', sourceType: 'blogger' },
  { handle: 'lexfridman', name: 'Lex Fridman', description: 'AI 播客与访谈', sourceType: 'blogger' },
  { handle: 'JimFan0924', name: 'Jim Fan', description: 'NVIDIA 高级 AI 科学家', sourceType: 'blogger' },
  { handle: 'bfchollet', name: 'François Chollet', description: 'Keras 作者，ARC 基准', sourceType: 'blogger' },
  { handle: 'satabor', name: 'Sébastien Bubeck', description: '微软研究院，Sparks of AGI', sourceType: 'blogger' },
  { handle: 'jasonwei20', name: 'Jason Wei', description: 'OpenAI 研究员，思维链', sourceType: 'blogger' },
  { handle: 'rasbt', name: 'Sebastian Raschka', description: '机器学习教育与实践', sourceType: 'blogger' },
  { handle: 'NathanBenaich', name: 'Nathan Benaich', description: 'Air Street Capital，State of AI', sourceType: 'blogger' },
  { handle: 'signulll', name: 'Vipul Ved Prakash', description: 'Together AI 创始人', sourceType: 'blogger' },
  { handle: 'elonmusk', name: 'Elon Musk', description: 'xAI / Tesla / SpaceX', sourceType: 'blogger' },
  { handle: 'gdb', name: 'Greg Brockman', description: 'OpenAI 联合创始人兼总裁', sourceType: 'blogger' },
  { handle: 'noamshazeer', name: 'Noam Shazeer', description: 'Character.AI 联合创始人', sourceType: 'blogger' },
  { handle: 'mustafasuleyman', name: 'Mustafa Suleyman', description: 'Microsoft AI CEO', sourceType: 'blogger' },
  { handle: 'tejasdkulkarni', name: 'Tejas Kulkarni', description: 'Common Sense Machines', sourceType: 'blogger' },
  { handle: '_akhaliq', name: 'AK', description: 'AI 论文速递', sourceType: 'blogger' },
  { handle: 'kaifulee', name: 'Kai-Fu Lee', description: '创新工场董事长', sourceType: 'blogger' },
  { handle: 'yasharahimi', name: 'Yashar Behzadi', description: 'Synthesis AI 创始人', sourceType: 'blogger' },
  { handle: 'benln', name: 'Ben Tossell', description: "Ben's Bites 创始人", sourceType: 'blogger' },
  { handle: 'teven', name: 'Teven Le Scao', description: 'Hugging Face 研究科学家', sourceType: 'blogger' },
  { handle: 'clefourrier', name: 'Clémentine Fourrier', description: 'Hugging Face 开源评估', sourceType: 'blogger' },
  { handle: 'reach_vb', name: 'Vaibhav Srivastav', description: 'Hugging Face 开发者关系', sourceType: 'blogger' },
  { handle: 'goodside', name: 'Riley Goodside', description: 'Scale AI 提示工程', sourceType: 'blogger' },
  { handle: 'willdepue', name: 'Will Depue', description: 'OpenAI 研究员', sourceType: 'blogger' },
  { handle: 'dotey', name: '宝玉', description: 'AI 产品与大模型实践', sourceType: 'blogger' },
  { handle: 'op7418', name: '歸藏', description: 'AI 工具与产品观察', sourceType: 'blogger' },
  { handle: 'satnam6502', name: 'Satnam Singh', description: 'Google 工程师，TPU / ML', sourceType: 'blogger' },
  { handle: 'PaulineLuc', name: 'Pauline Luc', description: 'Meta FAIR 研究科学家', sourceType: 'blogger' },
  { handle: 'teortaxesTex', name: 'Teortaxes', description: 'AI 安全与对齐讨论', sourceType: 'blogger' },
  { handle: 'faris', name: 'Faris Del Valle', description: 'AI 创业与产品', sourceType: 'blogger' },
  { handle: 'AndrewCurran_', name: 'Andrew Curran', description: 'AI 行业新闻', sourceType: 'blogger' },
  { handle: 'roamaneth', name: 'Roma Shah', description: 'AI 投资与趋势', sourceType: 'blogger' },
  { handle: 'ghosh_ishani', name: 'Ishani Ghosh', description: 'AI 政策与伦理', sourceType: 'blogger' },
  { handle: 'Lakshman603', name: 'Lakshman', description: 'AI 工程教程与实践', sourceType: 'blogger' },
  { handle: 'ylel65536', name: 'Guillaume Verdon', description: 'Extropic AI，量子机器学习', sourceType: 'blogger' },
  { handle: 'danielaamodei', name: 'Daniela Amodei', description: 'Anthropic 总裁', sourceType: 'blogger' },
  { handle: 'zuck', name: 'Mark Zuckerberg', description: 'Meta CEO，Llama 开源', sourceType: 'blogger' },
  { handle: 'paulg', name: 'Paul Graham', description: 'Y Combinator，AI 创业', sourceType: 'blogger' },
  { handle: 'sundarpichai', name: 'Sundar Pichai', description: 'Google / Alphabet CEO', sourceType: 'blogger' },
  { handle: 'satyanadella', name: 'Satya Nadella', description: 'Microsoft CEO', sourceType: 'blogger' },
  { handle: 'jackclarksf', name: 'Jack Clark', description: 'Anthropic 联创，Import AI', sourceType: 'blogger' },
  { handle: 'OpenAI', name: 'OpenAI', description: 'OpenAI 官方', sourceType: 'media' },
  { handle: 'AnthropicAI', name: 'Anthropic', description: 'Anthropic 官方', sourceType: 'media' },
  { handle: 'GoogleDeepMind', name: 'Google DeepMind', description: 'Google DeepMind 官方', sourceType: 'media' },
  { handle: 'huggingface', name: 'Hugging Face', description: 'Hugging Face 官方', sourceType: 'media' },
  { handle: 'MetaAI', name: 'Meta AI', description: 'Meta AI 官方', sourceType: 'media' },
  { handle: 'xai', name: 'xAI', description: 'xAI 官方', sourceType: 'media' },
  { handle: 'MistralAI', name: 'Mistral AI', description: 'Mistral AI 官方', sourceType: 'media' },
  { handle: 'stabilityai', name: 'Stability AI', description: 'Stability AI 官方', sourceType: 'media' },
  { handle: 'nvidia', name: 'NVIDIA', description: 'NVIDIA AI 官方', sourceType: 'media' },
  { handle: 'DeepLearningAI', name: 'DeepLearning.AI', description: 'Andrew Ng 旗下 AI 教育', sourceType: 'media' },
  { handle: 'weights_biases', name: 'Weights & Biases', description: 'MLOps 与实验追踪', sourceType: 'media' },
  { handle: 'lmsysorg', name: 'LMSYS Org', description: 'Chatbot Arena / 模型评测', sourceType: 'media' },
  { handle: 'gradio', name: 'Gradio', description: 'ML 演示与部署工具', sourceType: 'media' },
  { handle: 'perplexity_ai', name: 'Perplexity', description: 'Perplexity AI 官方', sourceType: 'media' },
  { handle: 'cohere', name: 'Cohere', description: 'Cohere 官方', sourceType: 'media' },
  { handle: 'cursor_ai', name: 'Cursor', description: 'Cursor AI IDE 官方', sourceType: 'media' },
  { handle: 'Replit', name: 'Replit', description: 'Replit AI 编程平台', sourceType: 'media' },
  { handle: 'scale_ai', name: 'Scale AI', description: 'Scale AI 官方', sourceType: 'media' },
  { handle: 'ai21labs', name: 'AI21 Labs', description: 'AI21 Labs 官方', sourceType: 'media' },
  { handle: 'allen_ai', name: 'Allen Institute for AI', description: 'Ai2 研究机构', sourceType: 'academic' },
  { handle: 'GoogleAI', name: 'Google AI', description: 'Google AI 官方', sourceType: 'media' },
  { handle: 'paperswithcode', name: 'Papers With Code', description: '论文与代码索引', sourceType: 'media' },
  { handle: 'CohereForAI', name: 'Cohere For AI', description: 'Cohere 开源研究', sourceType: 'academic' },
  { handle: 'modal_labs', name: 'Modal', description: '云端 AI 计算平台', sourceType: 'media' },
  { handle: 'togethercompute', name: 'Together AI', description: '开源模型推理平台', sourceType: 'media' },
  { handle: 'groqinc', name: 'Groq', description: 'Groq LPU 推理芯片', sourceType: 'media' },
  { handle: 'databricks', name: 'Databricks', description: '数据与 AI 平台', sourceType: 'media' },
  { handle: 'ElevenLabs_IO', name: 'ElevenLabs', description: '语音合成 AI', sourceType: 'media' },
  { handle: 'runwayml', name: 'Runway', description: '生成式视频 AI', sourceType: 'media' },
  { handle: 'midjourney', name: 'Midjourney', description: '图像生成 AI', sourceType: 'media' },
  { handle: 'futureoflife', name: 'Future of Life Institute', description: 'AI 安全与治理', sourceType: 'academic' },
  { handle: 'AISafetyMemes', name: 'AI Safety Memes', description: 'AI 安全社区', sourceType: 'blogger' },
  { handle: 'centre4res', name: 'Centre for AI Safety', description: 'AI 安全研究中心', sourceType: 'academic' },
  { handle: 'StanfordHAI', name: 'Stanford HAI', description: '斯坦福人本 AI 研究院', sourceType: 'academic' },
  { handle: 'MIT_CSAIL', name: 'MIT CSAIL', description: 'MIT 计算机与 AI 实验室', sourceType: 'academic' },
  { handle: 'Berkeley_AI', name: 'Berkeley AI Research', description: '伯克利 AI 研究', sourceType: 'academic' },
  { handle: 'ollama', name: 'Ollama', description: '本地大模型运行', sourceType: 'media' },
  { handle: 'ycombinator', name: 'Y Combinator', description: 'YC 孵化器，AI 创业', sourceType: 'media' },
  { handle: 'TechCrunch', name: 'TechCrunch', description: '科技媒体，AI 报道', sourceType: 'media' },
]

const _poolHandles = new Set(RECOMMENDATION_POOL.map((r) => r.handle.toLowerCase()))
if (RECOMMENDATION_POOL.length !== 100 || _poolHandles.size !== 100) {
  throw new Error(
    `RECOMMENDATION_POOL 须为 100 个不重复 handle，当前 ${RECOMMENDATION_POOL.length} 条 / ${_poolHandles.size} 个唯一 handle`
  )
}
